/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {

        if (args.length > 0) {
            if (args[0].equals("triangulo")) {
                int segundoArg = Integer.parseInt(args[1]);
                String repetir = "*".repeat(segundoArg);
                System.out.println(repetir);

            } else if (args[0].equals("losango")) {
                System.out.println("Quadrado");
            } else if (args[0].equals("retangulo")) {
                System.out.println("Circulo");
            } else {
                System.out.println("Forma não reconhecida");
            }
        }

    }
}
